dev.langchain4j.cdi.plugin.chat-model.class=dev.langchain4j.cdi.integrationtests.ChatModelMock
dev.langchain4j.cdi.plugin.thinking-model.class=dev.langchain4j.cdi.integrationtests.ThinkingChatModelMock

# Helidon server configuration
server.port=0

